services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
    restart: on-failure

  stats-db:
    image: postgres:16.1
    container_name: stat-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user


